### ISSUE TITLE
Seems to disable the repopulating of fields

### ISSUE THREAD

**Issue by ericnkatz** [GCX/acf-address-field#1]
Not sure how to go about investigating, but I have custom post type set up to accept address via this add-on but after saving the post, the address and other textarea posts do no repopulate to display the saved data for each text field.

**Comment by Omicron7** [comment]
I just ran through the add-on and didn't encounter any errors.  Can you give me some steps to reproduce this, or possibly any php errors thrown.

Here is what I've done to attempt to replicate this:
1. Create a custom post type (supports title and revisions)
2. Using Advanced custom Fields, I created a field group that included an address field and set the rules to show the field group when Post Type is equal to my custom post type.
3. Created a new post in the custom post type, added values to all the address field components and published the post.
4. Edited the created post, all  address components were populated with the previously saved values.

**Comment by iunificationist** [comment]
include_once( rtrim( dirname( **FILE** ), '/' ) . '/acf-address-field/address-field.php' );
when I insert this line into my functions.php of my theme includes

then I get this error
Warning: Cannot modify header information - headers already sent by (output started at /home/content/02/8916902/html/tplv/wp-content/plugins/advanced-custom-fields/acf.php:1759) in /home/content/02/8916902/html/tplv/wp-includes/pluggable.php on line 866

**Comment by Omicron7** [comment]
the include_once in the examples is just that, an example. Make sure the path and filename to the address-field.php file is correct for your system. The error you are seeing is probably due to php outputting an error saying it cant find the included file.
