### ISSUE TITLE
Fatal error: Internal Zend error

### ISSUE THREAD

**Issue by jonesch** [GCX/acf-address-field#12]
Occasionally, I am getting a "
Fatal error: Internal Zend error - Missing class information for in /home/content/10/8998810/html/powercurbers.com/wp-content/themes/powercurbers/library/plugin-add-ons/acf-address/address-field.php on line 499" error.

There is no rhyme or reason when it shows up, just periodically.

Any thoughts?
Thanks!

**Comment by grimmwerks** [comment]
I'm having the same issue on godaddy - did you figure it out?

**Comment by jonesch** [comment]
Come to find out that this extension uses a good bit of resources, and we found that if we increased the PHP Memory Limit from 32MB to 64 or above, it fixed the issue. We were on a dedicated server, so it was easy for us, but if you are on a shared server, it may pose more of an issue.
Hope this helps!

**Comment by grimmwerks** [comment]
Thanks!
