### ISSUE TITLE
Nothing happens with ACF and acf-address-field activate..

### ISSUE THREAD

**Issue by ghost** [GCX/acf-address-field#19]
WP v3.5.2 (FR)
ACF v4.1.8.1

I try both plugins and theme inclusion installations and I didn't see anything in the 'type field' selectbox.

Is the plugin broke up with the ACF or WP new versions ? Anyone got that issue ?

**Comment by Omicron7** [comment]
This plugin does not work with ACF v4.0 and higher. Check out some of the forks, I believe others have updated it.
