### ISSUE TITLE
URLs are broken on Windows hosts

### ISSUE THREAD

**Issue by Omicron7** [GCX/acf-address-field#4]
Original issue was described in #2:

from @michapixel

> I'm on wp 3.3.2 and use ACF Version 3.1.7 and i get errors like:
> "NetworkError: 403 Forbidden - http://localhost/wordpress_test/D:wampwwwwordpress_testwp-contentpluginsacf-address-field/address-field.css?ver=3.3.2"

**Comment by Omicron7** [comment]
I'm installing a windows VM with wordpress to try to get this figured out.
Information that would help solve this would be:
- PHP Version.
- WordPress version.
- Values of:
  - ABSPATH
  - ACF_Address_Field::singleton()->base_dir
  - ACF_Address_Field::singleton()->base_uri_rel
  - if possible value of `__FILE__` for address-field.php

**Comment by michapixel** [comment]
wp: 3.3.2
php: 5.3.9
ABSPATH: "D:\wamp\www\wordpress_test/"
base_dir: "D:\wamp\www\wordpress_test\wp-content\plugins\advanced-custom-fields-address-field-add-on"
base_uri_rel: "/D:/wamp/www/wordpress_test/wp-content/plugins/advanced-custom-fields-address-field-add-on"
**FILE**: "D:\wamp\www\wordpress_test\wp-content\plugins\advanced-custom-fields-address-field-add-on\address-field.php"

**Comment by Omicron7** [comment]
Ahh, I see the issue.  WordPress is adding a trailing slash to the ABSPATH that I'm not stripping off when doing string comparisons. Changing line 99 from
`$root = array_pop( explode( DIRECTORY_SEPARATOR, rtrim( ABSPATH, DIRECTORY_SEPARATOR ) ) );`
to
`$root = array_pop( explode( DIRECTORY_SEPARATOR, rtrim( ABSPATH, '/' ) ) );`
fixed it for my Windows VM.

**Comment by michapixel** [comment]
let me try it quickly ....

**Comment by michapixel** [comment]
yup much better now.

**Comment by Omicron7** [comment]
ok, I'll get that merged into the development branch, it might be a bit before I can get a new version pushed to the WordPress plugin repo.
